version: '3.9'

services:
  web:
    build: .
    network_mode: "host"
#    command: uvicorn app.main:app --host "0.0.0.0" --port 8080
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    restart: unless-stopped
    image: postgres:14.2
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=${DATABASE_URL}
volumes:
  postgres:
